### ISSUE TITLE
Implement Logging - SLF4J?

### ISSUE THREAD

**Issue by Pitterling** [vlsi/ksar#77]
currently System.out.println and System.err.println statements and a few Logger.getLogger(My class.getName()).log(Level.SEVERE, null, ex) statements are used for logging purpose.

ToDo: implement consistent logging facility

I never used the Java Logging options, but what i read so far - SLF4J - seems to be a good choice.

What do you think ?

**Comment by Vest** [comment]
I would say, slf4j is pretty easy to use, but in one of my projects I have started using Apache log4j2. Internet says different things, e.g. the same author from slf4j contributes to log4j2.
Currently I see slf4j has an experimental support for Java 9, but I don't see the same about log4j2. Maybe it should work out-of-the-box.

I'd use log4j2, because this is something new to me and I like challenges :)

**Comment by Pitterling** [comment]
@vlsi any thoughts ??

**Comment by vlsi** [comment]
Frankly speaking, I've never used log4j2, however it sounds just the right thing :)
